; Animation constants
RSRESET
DEF ANIM_SPRITE_ID         RB
DEF ANIM_PALETTE_ID        RB
DEF ANIM_SPRITE_ANIM_ID    RB
DEF ANIM_SPRITE_ANIM_FLAGS RB
DEF ANIM_SOUND_FX_ID       RB

; Sprite animation IDs
	const_def
	const SPRITE_ANIM_LIGHT_NPC_UP
	const SPRITE_ANIM_LIGHT_NPC_RIGHT
	const SPRITE_ANIM_LIGHT_NPC_DOWN
	const SPRITE_ANIM_LIGHT_NPC_LEFT
	const SPRITE_ANIM_DARK_NPC_UP
	const SPRITE_ANIM_DARK_NPC_RIGHT
	const SPRITE_ANIM_DARK_NPC_DOWN
	const SPRITE_ANIM_DARK_NPC_LEFT
	const SPRITE_ANIM_BLUE_NPC_UP
	const SPRITE_ANIM_BLUE_NPC_RIGHT
	const SPRITE_ANIM_BLUE_NPC_DOWN
	const SPRITE_ANIM_BLUE_NPC_LEFT
	const SPRITE_ANIM_PINK_NPC_UP
	const SPRITE_ANIM_PINK_NPC_RIGHT
	const SPRITE_ANIM_PINK_NPC_DOWN
	const SPRITE_ANIM_PINK_NPC_LEFT
	const SPRITE_ANIM_YELLOW_NPC_UP
	const SPRITE_ANIM_YELLOW_NPC_RIGHT
	const SPRITE_ANIM_YELLOW_NPC_DOWN
	const SPRITE_ANIM_YELLOW_NPC_LEFT
	const SPRITE_ANIM_GREEN_NPC_UP
	const SPRITE_ANIM_GREEN_NPC_RIGHT
	const SPRITE_ANIM_GREEN_NPC_DOWN
	const SPRITE_ANIM_GREEN_NPC_LEFT
	const SPRITE_ANIM_RED_NPC_UP
	const SPRITE_ANIM_RED_NPC_RIGHT
	const SPRITE_ANIM_RED_NPC_DOWN
	const SPRITE_ANIM_RED_NPC_LEFT
	const SPRITE_ANIM_PURPLE_NPC_UP
	const SPRITE_ANIM_PURPLE_NPC_RIGHT
	const SPRITE_ANIM_PURPLE_NPC_DOWN
	const SPRITE_ANIM_PURPLE_NPC_LEFT
	const SPRITE_ANIM_WHITE_NPC_UP
	const SPRITE_ANIM_WHITE_NPC_RIGHT
	const SPRITE_ANIM_WHITE_NPC_DOWN
	const SPRITE_ANIM_WHITE_NPC_LEFT
	const SPRITE_ANIM_INDIGO_NPC_UP
	const SPRITE_ANIM_INDIGO_NPC_RIGHT
	const SPRITE_ANIM_INDIGO_NPC_DOWN
	const SPRITE_ANIM_INDIGO_NPC_LEFT
	const SPRITE_ANIM_AMY_LAYING
	const SPRITE_ANIM_AMY_STAND
	const SPRITE_ANIM_CLERK_NPC_UP
	const SPRITE_ANIM_CLERK_NPC_RIGHT
	const SPRITE_ANIM_CLERK_NPC_DOWN
	const SPRITE_ANIM_CLERK_NPC_LEFT
	const SPRITE_ANIM_VOLCANO_SMOKE
	const SPRITE_ANIM_OWMAP_CURSOR
	const SPRITE_ANIM_OWMAP_CURSOR_FAST
	const SPRITE_ANIM_TORCH
	const SPRITE_ANIM_CARD_TOP_LEFT
	const SPRITE_ANIM_CARD_TOP_RIGHT
	const SPRITE_ANIM_CARD_LEFT_SPARK
	const SPRITE_ANIM_CARD_BOTTOM_LEFT
	const SPRITE_ANIM_CARD_BOTTOM_RIGHT
	const SPRITE_ANIM_CARD_RIGHT_SPARK
	const SPRITE_ANIM_GLOW
	const SPRITE_ANIM_PARALYSIS
	const SPRITE_ANIM_SLEEP
	const SPRITE_ANIM_CONFUSION
	const SPRITE_ANIM_POISON
	const SPRITE_ANIM_SINGLE_HIT
	const SPRITE_ANIM_HIT
	const SPRITE_ANIM_BIG_HIT
	const SPRITE_ANIM_DAMAGE_0
	const SPRITE_ANIM_DAMAGE_1
	const SPRITE_ANIM_DAMAGE_2
	const SPRITE_ANIM_DAMAGE_3
	const SPRITE_ANIM_DAMAGE_4
	const SPRITE_ANIM_DAMAGE_5
	const SPRITE_ANIM_DAMAGE_6
	const SPRITE_ANIM_DAMAGE_7
	const SPRITE_ANIM_DAMAGE_8
	const SPRITE_ANIM_DAMAGE_9
	const SPRITE_ANIM_DAMAGE_ARROW
	const SPRITE_ANIM_DAMAGE_RESIST
	const SPRITE_ANIM_DAMAGE_WEAK
	const SPRITE_ANIM_THUNDER_SHOCK
	const SPRITE_ANIM_LIGHTNING
	const SPRITE_ANIM_BORDER_SPARK
	const SPRITE_ANIM_BIG_LIGHTNING
	const SPRITE_ANIM_SMALL_FLAME
	const SPRITE_ANIM_BIG_FLAME
	const SPRITE_ANIM_FIRE_SPIN
	const SPRITE_ANIM_DIVE_BOMB
	const SPRITE_ANIM_WATER_JETS
	const SPRITE_ANIM_WATER_GUN
	const SPRITE_ANIM_WHIRLPOOL
	const SPRITE_ANIM_HYDRO_PUMP
	const SPRITE_ANIM_BLIZZARD
	const SPRITE_ANIM_PSYCHIC
	const SPRITE_ANIM_LEER
	const SPRITE_ANIM_BEAM
	const SPRITE_ANIM_HYPER_BEAM
	const SPRITE_ANIM_ROCK_THROW
	const SPRITE_ANIM_STONE_BARRAGE
	const SPRITE_ANIM_PUNCH
	const SPRITE_ANIM_THUNDERPUNCH
	const SPRITE_ANIM_FIRE_PUNCH
	const SPRITE_ANIM_STRETCH_KICK
	const SPRITE_ANIM_SLASH
	const SPRITE_ANIM_WHIP
	const SPRITE_ANIM_SONICBOOM
	const SPRITE_ANIM_FURY_SWIPES
	const SPRITE_ANIM_DRILL
	const SPRITE_ANIM_POT_SMASH
	const SPRITE_ANIM_BONEMERANG
	const SPRITE_ANIM_SEISMIC_TOSS
	const SPRITE_ANIM_NEEDLES
	const SPRITE_ANIM_WHITE_GAS
	const SPRITE_ANIM_POWDER
	const SPRITE_ANIM_GOO
	const SPRITE_ANIM_BUBBLES
	const SPRITE_ANIM_STRING_SHOT
	const SPRITE_ANIM_BOYFRIENDS
	const SPRITE_ANIM_LURE
	const SPRITE_ANIM_TOXIC
	const SPRITE_ANIM_CONFUSE_RAY
	const SPRITE_ANIM_SING
	const SPRITE_ANIM_SUPERSONIC
	const SPRITE_ANIM_PETAL_DANCE
	const SPRITE_ANIM_PROTECT
	const SPRITE_ANIM_BARRIER
	const SPRITE_ANIM_SPEED
	const SPRITE_ANIM_WHIRLWIND
	const SPRITE_ANIM_CRY
	const SPRITE_ANIM_QUESTION_MARK
	const SPRITE_ANIM_SELFDESTRUCT
	const SPRITE_ANIM_BIG_SELFDESTRUCT_1
	const SPRITE_ANIM_HEAL
	const SPRITE_ANIM_DRAIN
	const SPRITE_ANIM_DARK_GAS
	const SPRITE_ANIM_BIG_SELFDESTRUCT_2
	const SPRITE_ANIM_GLOW_BENCH
	const SPRITE_ANIM_FIREGIVER_START
	const SPRITE_ANIM_HEALING_WIND
	const SPRITE_ANIM_WHIRLWIND_BENCH
	const SPRITE_ANIM_EXPAND
	const SPRITE_ANIM_CAT_PUNCH
	const SPRITE_ANIM_THUNDER_WAVE
	const SPRITE_ANIM_FIREGIVER_PLAYER
	const SPRITE_ANIM_FIREGIVER_OPP
	const SPRITE_ANIM_PLAYER_SHUFFLE
	const SPRITE_ANIM_OPP_SHUFFLE
	const SPRITE_ANIM_BOTH_SHUFFLE
	const SPRITE_ANIM_BOTH_DRAW
	const SPRITE_ANIM_PLAYER_DRAW
	const SPRITE_ANIM_OPP_DRAW
	const SPRITE_ANIM_COIN_SPIN
	const SPRITE_ANIM_COIN_TOSS_GOING_HEADS
	const SPRITE_ANIM_COIN_TOSS_GOING_TAILS
	const SPRITE_ANIM_COIN_TAILS
	const SPRITE_ANIM_COIN_HEADS
	const SPRITE_ANIM_DUEL_WIN
	const SPRITE_ANIM_DUEL_LOSS
	const SPRITE_ANIM_DUEL_DRAW
	const SPRITE_ANIM_FIREBALL
	const SPRITE_ANIM_CONTINUOUS_FIREBALL
	const SPRITE_ANIM_BENCH_MANIPULATION
	const SPRITE_ANIM_PSYCHIC_BEAM
	const SPRITE_ANIM_PSYCHIC_BEAM_BENCH
	const SPRITE_ANIM_BOULDER_SMASH
	const SPRITE_ANIM_MEGA_PUNCH
	const SPRITE_ANIM_PSYPUNCH
	const SPRITE_ANIM_SLUDGE_PUNCH
	const SPRITE_ANIM_ICE_PUNCH
	const SPRITE_ANIM_KICK
	const SPRITE_ANIM_TAIL_SLAP
	const SPRITE_ANIM_TAIL_WHIP
	const SPRITE_ANIM_SLAP
	const SPRITE_ANIM_QUESTION_MARK_BENCH
	const SPRITE_ANIM_SKULL_BASH
	const SPRITE_ANIM_COIN_HURL
	const SPRITE_ANIM_TELEPORT
	const SPRITE_ANIM_FOLLOW_ME
	const SPRITE_ANIM_SWIFT
	const SPRITE_ANIM_3D_ATTACK
	const SPRITE_ANIM_FOCUS_BLAST
	const SPRITE_ANIM_FOCUS_BLAST_BENCH
	const SPRITE_ANIM_BONE_TOSS_BENCH
	const SPRITE_ANIM_COIN_HURL_BENCH
	const SPRITE_ANIM_BIG_SNORE
	const SPRITE_ANIM_RAZOR_LEAF
	const SPRITE_ANIM_GUILLOTINE
	const SPRITE_ANIM_VINE_PULL
	const SPRITE_ANIM_PERPLEX
	const SPRITE_ANIM_NINE_TAILS
	const SPRITE_ANIM_BONE_HEADBUTT
	const SPRITE_ANIM_DRILL_DIVE
	const SPRITE_ANIM_DARK_SONG
	const SPRITE_ANIM_175
	const SPRITE_ANIM_176
	const SPRITE_ANIM_177
	const SPRITE_ANIM_178
	const SPRITE_ANIM_179
	const SPRITE_ANIM_180
	const SPRITE_ANIM_181
	const SPRITE_ANIM_182
	const SPRITE_ANIM_183
	const SPRITE_ANIM_184
	const SPRITE_ANIM_185
	const SPRITE_ANIM_186
	const SPRITE_ANIM_187
	const SPRITE_ANIM_188
	const SPRITE_ANIM_189
	const SPRITE_ANIM_190
	const SPRITE_ANIM_191
	const SPRITE_ANIM_192
	const SPRITE_ANIM_193
	const SPRITE_ANIM_194
	const SPRITE_ANIM_195
	const SPRITE_ANIM_196
	const SPRITE_ANIM_197
	const SPRITE_ANIM_198
	const SPRITE_ANIM_199
	const SPRITE_ANIM_200
	const SPRITE_ANIM_201
	const SPRITE_ANIM_202
	const SPRITE_ANIM_203
	const SPRITE_ANIM_204
	const SPRITE_ANIM_205
	const SPRITE_ANIM_206
	const SPRITE_ANIM_207
	const SPRITE_ANIM_208
	const SPRITE_ANIM_209
	const SPRITE_ANIM_210
	const SPRITE_ANIM_211
	const SPRITE_ANIM_212
	const SPRITE_ANIM_213
	const SPRITE_ANIM_214
	const SPRITE_ANIM_215
	const SPRITE_ANIM_216

DEF NUM_SPRITE_ANIMS EQU const_value

; Animation duel screen constants (see wDuelAnimationScreen)
	const_def
	const DUEL_ANIM_SCREEN_MAIN_SCENE
	const DUEL_ANIM_SCREEN_PLAYER_PLAY_AREA
	const DUEL_ANIM_SCREEN_OPP_PLAY_AREA

	const_def
	; Normal animations
	const DUEL_ANIM_NONE
	const DUEL_ANIM_GLOW
	const DUEL_ANIM_PARALYSIS
	const DUEL_ANIM_SLEEP
	const DUEL_ANIM_CONFUSION
	const DUEL_ANIM_POISON
	const DUEL_ANIM_SINGLE_HIT
	const DUEL_ANIM_HIT
	const DUEL_ANIM_BIG_HIT
	const DUEL_ANIM_SHOW_DAMAGE
	const DUEL_ANIM_THUNDER_SHOCK
	const DUEL_ANIM_LIGHTNING
	const DUEL_ANIM_BORDER_SPARK
	const DUEL_ANIM_BIG_LIGHTNING
	const DUEL_ANIM_SMALL_FLAME
	const DUEL_ANIM_BIG_FLAME
	const DUEL_ANIM_FIRE_SPIN
	const DUEL_ANIM_DIVE_BOMB
	const DUEL_ANIM_WATER_JETS
	const DUEL_ANIM_WATER_GUN
	const DUEL_ANIM_WHIRLPOOL
	const DUEL_ANIM_HYDRO_PUMP
	const DUEL_ANIM_BLIZZARD
	const DUEL_ANIM_PSYCHIC
	const DUEL_ANIM_LEER
	const DUEL_ANIM_BEAM
	const DUEL_ANIM_HYPER_BEAM
	const DUEL_ANIM_ROCK_THROW
	const DUEL_ANIM_STONE_BARRAGE
	const DUEL_ANIM_PUNCH
	const DUEL_ANIM_THUNDERPUNCH
	const DUEL_ANIM_FIRE_PUNCH
	const DUEL_ANIM_STRETCH_KICK
	const DUEL_ANIM_SLASH
	const DUEL_ANIM_WHIP
	const DUEL_ANIM_SONICBOOM
	const DUEL_ANIM_FURY_SWIPES
	const DUEL_ANIM_DRILL
	const DUEL_ANIM_POT_SMASH
	const DUEL_ANIM_BONEMERANG
	const DUEL_ANIM_SEISMIC_TOSS
	const DUEL_ANIM_NEEDLES
	const DUEL_ANIM_WHITE_GAS
	const DUEL_ANIM_POWDER
	const DUEL_ANIM_GOO
	const DUEL_ANIM_BUBBLES
	const DUEL_ANIM_STRING_SHOT
	const DUEL_ANIM_BOYFRIENDS
	const DUEL_ANIM_LURE
	const DUEL_ANIM_TOXIC
	const DUEL_ANIM_CONFUSE_RAY
	const DUEL_ANIM_SING
	const DUEL_ANIM_SUPERSONIC
	const DUEL_ANIM_PETAL_DANCE
	const DUEL_ANIM_PROTECT
	const DUEL_ANIM_BARRIER
	const DUEL_ANIM_SPEED
	const DUEL_ANIM_WHIRLWIND
	const DUEL_ANIM_CRY
	const DUEL_ANIM_QUESTION_MARK
	const DUEL_ANIM_SELFDESTRUCT
	const DUEL_ANIM_BIG_SELFDESTRUCT_1
	const DUEL_ANIM_HEAL
	const DUEL_ANIM_DRAIN
	const DUEL_ANIM_DARK_GAS
	const DUEL_ANIM_BIG_SELFDESTRUCT_2
	const DUEL_ANIM_BENCH_THUNDER
	const DUEL_ANIM_QUICKFREEZE
	const DUEL_ANIM_BENCH_GLOW
	const DUEL_ANIM_FIREGIVER_START
	const DUEL_ANIM_HEALING_WIND
	const DUEL_ANIM_BENCH_WHIRLWIND
	const DUEL_ANIM_EXPAND
	const DUEL_ANIM_CAT_PUNCH
	const DUEL_ANIM_THUNDER_WAVE
	const DUEL_ANIM_FIREGIVER_PLAYER
	const DUEL_ANIM_FIREGIVER_OPP
	const DUEL_ANIM_PLAYER_SHUFFLE
	const DUEL_ANIM_OPP_SHUFFLE
	const DUEL_ANIM_BOTH_SHUFFLE
	const DUEL_ANIM_BOTH_DRAW
	const DUEL_ANIM_PLAYER_DRAW
	const DUEL_ANIM_OPP_DRAW
	const DUEL_ANIM_COIN_SPIN
	const DUEL_ANIM_COIN_TOSS_GOING_HEADS
	const DUEL_ANIM_COIN_TOSS_GOING_TAILS
	const DUEL_ANIM_COIN_TAILS
	const DUEL_ANIM_COIN_HEADS
	const DUEL_ANIM_DUEL_WIN
	const DUEL_ANIM_DUEL_LOSS
	const DUEL_ANIM_DUEL_DRAW
	const DUEL_ANIM_FIREBALL
	const DUEL_ANIM_CONTINUOUS_FIREBALL
	const DUEL_ANIM_BENCH_MANIPULATION
	const DUEL_ANIM_PSYCHIC_BEAM
	const DUEL_ANIM_PSYCHIC_BEAM_BENCH
	const DUEL_ANIM_BOULDER_SMASH
	const DUEL_ANIM_MEGA_PUNCH
	const DUEL_ANIM_PSYPUNCH
	const DUEL_ANIM_SLUDGE_PUNCH
	const DUEL_ANIM_ICE_PUNCH
	const DUEL_ANIM_KICK
	const DUEL_ANIM_TAIL_SLAP
	const DUEL_ANIM_TAIL_WHIP
	const DUEL_ANIM_SLAP
	const DUEL_ANIM_QUESTION_MARK_BENCH
	const DUEL_ANIM_SKULL_BASH
	const DUEL_ANIM_COIN_HURL
	const DUEL_ANIM_TELEPORT
	const DUEL_ANIM_FOLLOW_ME
	const DUEL_ANIM_SWIFT
	const DUEL_ANIM_3D_ATTACK
	const DUEL_ANIM_DRY_UP
	const DUEL_ANIM_FOCUS_BLAST
	const DUEL_ANIM_FOCUS_BLAST_BENCH
	const DUEL_ANIM_BONE_TOSS_BENCH
	const DUEL_ANIM_COIN_HURL_BENCH
	const DUEL_ANIM_BIG_SNORE
	const DUEL_ANIM_RAZOR_LEAF
	const DUEL_ANIM_GUILLOTINE
	const DUEL_ANIM_VINE_PULL
	const DUEL_ANIM_PERPLEX
	const DUEL_ANIM_NINE_TAILS
	const DUEL_ANIM_BONE_HEADBUTT
	const DUEL_ANIM_DRILL_DIVE
	const DUEL_ANIM_DARK_SONG

DEF NUM_REGULAR_DUEL_ANIMS EQU const_value

	; animations passed this point are treated differently
DEF DUEL_SPECIAL_ANIMS EQU const_value

DEF DUEL_SCREEN_ANIMS EQU const_value
	const DUEL_ANIM_SMALL_SHAKE_X      ; $61
	const DUEL_ANIM_BIG_SHAKE_X        ; $62
	const DUEL_ANIM_SMALL_SHAKE_Y      ; $63
	const DUEL_ANIM_BIG_SHAKE_Y        ; $64
	const DUEL_ANIM_FLASH              ; $65
	const DUEL_ANIM_DISTORT            ; $66

	; this animation is only played within DUEL_ANIM_PRINT_DAMAGE
	const_def $8c
	const DUEL_ANIM_DAMAGE_HUD         ; $8c

	const_def $96
	const DUEL_ANIM_SET_SCREEN         ; $96
	const DUEL_ANIM_PRINT_DAMAGE       ; $97
	const DUEL_ANIM_UPDATE_HUD         ; $98
	const DUEL_ANIM_153_UNUSED         ; $99
	const DUEL_ANIM_154_UNUSED         ; $9a
	const DUEL_ANIM_155_UNUSED         ; $9b
	const DUEL_ANIM_156_UNUSED         ; $9c
	const DUEL_ANIM_157_UNUSED         ; $9d
	const DUEL_ANIM_158_UNUSED         ; $9e

	; Special animations
	const_def $fa
	const DUEL_ANIM_SHAKE1             ; $fa
	const DUEL_ANIM_SHAKE2             ; $fb
	const DUEL_ANIM_SHAKE3             ; $fc

	; Duel Anim Struct constants
RSRESET
DEF DUEL_ANIM_STRUCT_ID             RB ; $0
DEF DUEL_ANIM_STRUCT_SCREEN         RB ; $1
DEF DUEL_ANIM_STRUCT_DUELIST_SIDE   RB ; $2
DEF DUEL_ANIM_STRUCT_LOCATION_PARAM RB ; $3
DEF DUEL_ANIM_STRUCT_DAMAGE         RW ; $4
DEF DUEL_ANIM_STRUCT_UNKNOWN_2      RB ; $6
DEF DUEL_ANIM_STRUCT_BANK           RB ; $7
DEF DUEL_ANIM_STRUCT_SIZE EQU _RS

	; ow_frame struct constants
RSRESET
DEF OW_FRAME_STRUCT_DURATION         RB ; $0
DEF OW_FRAME_STRUCT_VRAM_TILE_OFFSET RB ; $1
DEF OW_FRAME_STRUCT_VRAM_BANK        RB ; $2
DEF OW_FRAME_STRUCT_TILESET_BANK     RB ; $3
DEF OW_FRAME_STRUCT_TILESET          RW ; $4
DEF OW_FRAME_STRUCT_TILESET_OFFSET   RW ; $6
DEF OW_FRAME_STRUCT_SIZE EQU _RS

DEF NUM_OW_FRAMESET_SUBGROUPS EQU 3

DEF SET_ANIM_SCREEN_MAIN      EQU $1
DEF SET_ANIM_SCREEN_PLAY_AREA EQU $4
