	const_def
	const PORTRAIT_PLAYER
	const PORTRAIT_RONALD
	const PORTRAIT_SAM
	const PORTRAIT_IMAKUNI
	const PORTRAIT_NIKKI
	const PORTRAIT_RICK
	const PORTRAIT_KEN
	const PORTRAIT_AMY
	const PORTRAIT_ISAAC
	const PORTRAIT_MITCH
	const PORTRAIT_GENE
	const PORTRAIT_MURRAY
	const PORTRAIT_COURTNEY
	const PORTRAIT_STEVE
	const PORTRAIT_JACK
	const PORTRAIT_ROD
	const PORTRAIT_JOSEPH
	const PORTRAIT_DAVID
	const PORTRAIT_ERIK
	const PORTRAIT_JOHN
	const PORTRAIT_ADAM
	const PORTRAIT_JONATHAN
	const PORTRAIT_JOSHUA
	const PORTRAIT_NICHOLAS
	const PORTRAIT_BRANDON
	const PORTRAIT_MATTHEW
	const PORTRAIT_RYAN
	const PORTRAIT_ANDREW
	const PORTRAIT_CHRIS
	const PORTRAIT_MICHAEL
	const PORTRAIT_DANIEL
	const PORTRAIT_ROBERT
	const PORTRAIT_BRITTANY
	const PORTRAIT_KRISTIN
	const PORTRAIT_HEATHER
	const PORTRAIT_SARA
	const PORTRAIT_AMANDA
	const PORTRAIT_JENNIFER
	const PORTRAIT_JESSICA
	const PORTRAIT_STEPHANIE
	const PORTRAIT_AARON
DEF NUM_PORTRAITS EQU const_value

DEF PORTRAIT_SLOT_1 EQU $d0
DEF PORTRAIT_SLOT_2 EQU $a0

	const_def
	const EMOTION_NEUTRAL
	const EMOTION_HAPPY
	const EMOTION_SAD
