; wSpriteAnimBuffer
DEF SPRITE_ANIM_BUFFER_CAPACITY EQU 16 ; sprites

; sprite_anim_struct constants
	const_def
	const SPRITE_ANIM_ENABLED
	const SPRITE_ANIM_ATTRIBUTES
	const SPRITE_ANIM_COORD_X
	const SPRITE_ANIM_COORD_Y
	const SPRITE_ANIM_TILE_ID
	const SPRITE_ANIM_ID
	const SPRITE_ANIM_BANK
	const SPRITE_ANIM_POINTER
	const_skip ; pointer
	const SPRITE_ANIM_FRAME_OFFSET_POINTER
	const_skip ; pointer
	const SPRITE_ANIM_FRAME_BANK
	const SPRITE_ANIM_FRAME_DATA_POINTER
	const_skip ; pointer
	const SPRITE_ANIM_COUNTER
	const SPRITE_ANIM_FLAGS
DEF SPRITE_ANIM_LENGTH EQU const_value

; SPRITE_ANIM_FLAGS values
	const_def
	const SPRITE_ANIM_FLAG_X_INVERTED_F  ; $0
	const SPRITE_ANIM_FLAG_Y_INVERTED_F  ; $1
	const SPRITE_ANIM_FLAG_CENTERED_F    ; $2
	const SPRITE_ANIM_FLAG_3_F           ; $3
	const SPRITE_ANIM_FLAG_8x16_F        ; $4
	const SPRITE_ANIM_FLAG_X_FLIP_F      ; $5
	const SPRITE_ANIM_FLAG_Y_FLIP_F      ; $6
	const SPRITE_ANIM_FLAG_UNSKIPPABLE_F ; $7

DEF SPRITE_ANIM_FLAG_X_INVERTED  EQU 1 << SPRITE_ANIM_FLAG_X_INVERTED_F
DEF SPRITE_ANIM_FLAG_Y_INVERTED  EQU 1 << SPRITE_ANIM_FLAG_Y_INVERTED_F
DEF SPRITE_ANIM_FLAG_CENTERED    EQU 1 << SPRITE_ANIM_FLAG_CENTERED_F
DEF SPRITE_ANIM_FLAG_3           EQU 1 << SPRITE_ANIM_FLAG_3_F
DEF SPRITE_ANIM_FLAG_8x16        EQU 1 << SPRITE_ANIM_FLAG_8x16_F
DEF SPRITE_ANIM_FLAG_X_FLIP      EQU 1 << SPRITE_ANIM_FLAG_X_FLIP_F
DEF SPRITE_ANIM_FLAG_Y_FLIP      EQU 1 << SPRITE_ANIM_FLAG_Y_FLIP_F
DEF SPRITE_ANIM_FLAG_UNSKIPPABLE EQU 1 << SPRITE_ANIM_FLAG_UNSKIPPABLE_F

DEF SPRITE_FRAME_OFFSET_SIZE EQU 4

	const_def
	const SPRITE_OW_PLAYER
	const SPRITE_OW_RONALD
	const SPRITE_OW_DRMASON
	const SPRITE_OW_ISHIHARA
	const SPRITE_OW_IMAKUNI
	const SPRITE_OW_NIKKI
	const SPRITE_OW_RICK
	const SPRITE_OW_KEN
	const SPRITE_OW_AMY
	const SPRITE_OW_ISAAC
	const SPRITE_OW_MITCH
	const SPRITE_OW_GENE
	const SPRITE_OW_MURRAY
	const SPRITE_OW_COURTNEY
	const SPRITE_OW_STEVE
	const SPRITE_OW_JACK
	const SPRITE_OW_ROD
	const SPRITE_OW_BOY
	const SPRITE_OW_LAD
	const SPRITE_OW_SPECS
	const SPRITE_OW_BUTCH
	const SPRITE_OW_MANIA
	const SPRITE_OW_JOSHUA
	const SPRITE_OW_HOOD
	const SPRITE_OW_TECH
	const SPRITE_OW_CHAP
	const SPRITE_OW_MAN
	const SPRITE_OW_PAPPY
	const SPRITE_OW_GIRL
	const SPRITE_OW_LASS1
	const SPRITE_OW_LASS2
	const SPRITE_OW_LASS3
	const SPRITE_OW_SWIMMER
	const SPRITE_OW_CLERK
	const SPRITE_OW_GAL
	const SPRITE_OW_WOMAN
	const SPRITE_OW_GRANNY
	const SPRITE_OW_MAP_OAM
	const SPRITE_OW_TORCH
	const SPRITE_OW_LEGENDARY_CARD
	const SPRITE_BOOSTER_PACK_OAM
	const SPRITE_PRESS_START
	const SPRITE_GRASS
	const SPRITE_FIRE
	const SPRITE_WATER
	const SPRITE_COLORLESS
	const SPRITE_LIGHTNING
	const SPRITE_PSYCHIC
	const SPRITE_FIGHTING
	const SPRITE_DUEL_3D_ATTACK
	const SPRITE_DUEL_BALL
	const SPRITE_DUEL_BARRIER
	const SPRITE_DUEL_BEAM
	const SPRITE_DUEL_BENCH_MANIPULATION
	const SPRITE_DUEL_BIG_LIGHTNING
	const SPRITE_DUEL_BIG_SNORE
	const SPRITE_DUEL_BONE2
	const SPRITE_DUEL_BONE_HEADBUTT
	const SPRITE_DUEL_BONE
	const SPRITE_DUEL_BUBBLE
	const SPRITE_DUEL_CARD
	const SPRITE_DUEL_CAT_PAW
	const SPRITE_DUEL_COIN_HURL
	const SPRITE_DUEL_COIN
	const SPRITE_DUEL_CRY
	const SPRITE_DUEL_DAMAGE
	const SPRITE_DUEL_DARK_SONG
	const SPRITE_DUEL_DRAIN
	const SPRITE_DUEL_DRILL_DIVE
	const SPRITE_DUEL_DRILL
	const SPRITE_DUEL_EXPLOSION
	const SPRITE_DUEL_FIREBALLS
	const SPRITE_DUEL_FIRE_BIRD
	const SPRITE_DUEL_FIRE_SPIN
	const SPRITE_DUEL_FLAME
	const SPRITE_DUEL_FOCUS_BLAST_BENCH
	const SPRITE_DUEL_FOCUS_BLAST
	const SPRITE_DUEL_FOLLOW_ME
	const SPRITE_DUEL_GAS
	const SPRITE_DUEL_GLOW
	const SPRITE_DUEL_GOO
	const SPRITE_DUEL_GUILLOTINE
	const SPRITE_DUEL_HEAL
	const SPRITE_DUEL_HEART
	const SPRITE_DUEL_HIT
	const SPRITE_DUEL_HYDRO_PUMP
	const SPRITE_DUEL_HYPER_BEAM
	const SPRITE_DUEL_ICE_PUNCH
	const SPRITE_DUEL_KICK
	const SPRITE_DUEL_LEER
	const SPRITE_DUEL_LIGHTNING
	const SPRITE_DUEL_LURE
	const SPRITE_DUEL_MEGA_PUNCH
	const SPRITE_DUEL_NEEDLES
	const SPRITE_DUEL_NINE_TAILS
	const SPRITE_DUEL_NOTE
	const SPRITE_DUEL_PARALYSIS
	const SPRITE_DUEL_PERPLEX
	const SPRITE_DUEL_PETAL
	const SPRITE_DUEL_PLANET
	const SPRITE_DUEL_POISON
	const SPRITE_DUEL_POT
	const SPRITE_DUEL_POWDER
	const SPRITE_DUEL_PROTECT
	const SPRITE_DUEL_PSYCHIC_BEAM_BENCH
	const SPRITE_DUEL_PSYCHIC_BEAM
	const SPRITE_DUEL_PSYCHIC
	const SPRITE_DUEL_PSYPUNCH
	const SPRITE_DUEL_PUNCH
	const SPRITE_DUEL_QUESTION_MARK
	const SPRITE_DUEL_QUESTION_MARK_SMALL
	const SPRITE_DUEL_RAZOR_LEAF
	const SPRITE_DUEL_RESULT
	const SPRITE_DUEL_ROCK_THROW
	const SPRITE_DUEL_BOULDER
	const SPRITE_DUEL_SKULL_BASH
	const SPRITE_DUEL_SKULL
	const SPRITE_DUEL_SLAP
	const SPRITE_DUEL_SLASH
	const SPRITE_DUEL_SLEEP
	const SPRITE_DUEL_SLUDGE_PUNCH
	const SPRITE_DUEL_SMALL_GLOW
	const SPRITE_DUEL_SMALL_STAR
	const SPRITE_DUEL_SNOW
	const SPRITE_DUEL_SONICBOOM
	const SPRITE_DUEL_SOUND
	const SPRITE_DUEL_SPARK
	const SPRITE_DUEL_SPEED
	const SPRITE_DUEL_STAR
	const SPRITE_DUEL_STRETCH_KICK
	const SPRITE_DUEL_STRING
	const SPRITE_DUEL_SWIFT
	const SPRITE_DUEL_TAIL_SLAP
	const SPRITE_DUEL_TAIL_WHIP
	const SPRITE_DUEL_TELEPORT
	const SPRITE_DUEL_THUNDER
	const SPRITE_DUEL_VINE_PULL
	const SPRITE_DUEL_WATER_DROP
	const SPRITE_DUEL_WATER_GUN
	const SPRITE_DUEL_WAVE
	const SPRITE_DUEL_WHIP
	const SPRITE_DUEL_WHIRLPOOL
	const SPRITE_DUEL_WHIRLWIND
DEF NUM_SPRITES EQU const_value
