	const_def
	const TILEMAP_OVERWORLD_MAP                    ; $00
	const TILEMAP_MASON_LABORATORY                 ; $01
	const TILEMAP_CHALLENGE_MACHINE_MAP_EVENT      ; $02
	const TILEMAP_DECK_MACHINE_ROOM                ; $03
	const TILEMAP_DECK_MACHINE_MAP_EVENT           ; $04
	const TILEMAP_ISHIHARA                         ; $05
	const TILEMAP_FIGHTING_CLUB_ENTRANCE           ; $06
	const TILEMAP_ROCK_CLUB_ENTRANCE               ; $07
	const TILEMAP_WATER_CLUB_ENTRANCE              ; $08
	const TILEMAP_LIGHTNING_CLUB_ENTRANCE          ; $09
	const TILEMAP_GRASS_CLUB_ENTRANCE              ; $0a
	const TILEMAP_PSYCHIC_CLUB_ENTRANCE            ; $0b
	const TILEMAP_SCIENCE_CLUB_ENTRANCE            ; $0c
	const TILEMAP_FIRE_CLUB_ENTRANCE               ; $0d
	const TILEMAP_CHALLENGE_HALL_ENTRANCE          ; $0e
	const TILEMAP_CLUB_LOBBY                       ; $0f
	const TILEMAP_FIGHTING_CLUB                    ; $10
	const TILEMAP_ROCK_CLUB                        ; $11
	const TILEMAP_WATER_CLUB                       ; $12
	const TILEMAP_LIGHTNING_CLUB                   ; $13
	const TILEMAP_GRASS_CLUB                       ; $14
	const TILEMAP_PSYCHIC_CLUB                     ; $15
	const TILEMAP_SCIENCE_CLUB                     ; $16
	const TILEMAP_FIRE_CLUB                        ; $17
	const TILEMAP_CHALLENGE_HALL                   ; $18
	const TILEMAP_POKEMON_DOME_ENTRANCE            ; $19
	const TILEMAP_POKEMON_DOME_DOOR_MAP_EVENT      ; $1a
	const TILEMAP_POKEMON_DOME                     ; $1b
	const TILEMAP_HALL_OF_HONOR_DOOR_MAP_EVENT     ; $1c
	const TILEMAP_HALL_OF_HONOR                    ; $1d
	const TILEMAP_CARD_POP                         ; $1e
	const TILEMAP_GRASS_MEDAL                      ; $1f
	const TILEMAP_SCIENCE_MEDAL                    ; $20
	const TILEMAP_FIRE_MEDAL                       ; $21
	const TILEMAP_WATER_MEDAL                      ; $22
	const TILEMAP_LIGHTNING_MEDAL                  ; $23
	const TILEMAP_FIGHTING_MEDAL                   ; $24
	const TILEMAP_ROCK_MEDAL                       ; $25
	const TILEMAP_PSYCHIC_MEDAL                    ; $26
	const TILEMAP_GAMEBOY_LINK                     ; $27
	const TILEMAP_GAMEBOY_LINK_CONNECTING          ; $28
	const TILEMAP_GAMEBOY_PRINTER                  ; $29
	const TILEMAP_COLOSSEUM                        ; $2a
	const TILEMAP_EVOLUTION                        ; $2b
	const TILEMAP_MYSTERY                          ; $2c
	const TILEMAP_LABORATORY                       ; $2d
	const TILEMAP_CHARIZARD_INTRO                  ; $2e
	const TILEMAP_SCYTHER_INTRO                    ; $2f
	const TILEMAP_AERODACTYL_INTRO                 ; $30
	const TILEMAP_JAPANESE_TITLE_SCREEN            ; $31
	const TILEMAP_SOLID_TILES_1                    ; $32
	const TILEMAP_SOLID_TILES_2                    ; $33
	const TILEMAP_SOLID_TILES_3                    ; $34
	const TILEMAP_JAPANESE_TITLE_SCREEN_2          ; $35
	const TILEMAP_SOLID_TILES_4                    ; $36
	const TILEMAP_PLAYER                           ; $37
	const TILEMAP_OPPONENT                         ; $38
	const TILEMAP_TITLE_SCREEN                     ; $39
	const TILEMAP_COPYRIGHT                        ; $3a
	const TILEMAP_NINTENDO                         ; $3b
	const TILEMAP_COMPANIES                        ; $3c

DEF NUM_TILEMAPS EQU const_value
